# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout

      - run: go get -v -t -d ./...

      - run:
          name: Unit test
          command: go test -v ./...